"""visit model update

Revision ID: a3c23de60e47
Revises: 30ac36da2625
Create Date: 2025-04-10 11:37:42.060211

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a3c23de60e47'
down_revision = '30ac36da2625'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        # Step 1: Add user_id as nullable
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # Step 2: Populate user_id with values from marketer_id
    op.execute('UPDATE visits SET user_id = marketer_id')

    with op.batch_alter_table('visits', schema=None) as batch_op:
        # Step 3: Add NOT NULL constraint to user_id
        batch_op.alter_column('user_id', nullable=False)
        # Step 4: Drop the old index on marketer_id
        batch_op.drop_index('ix_visits_marketer_id')
        # Step 5: Create a new index on user_id
        batch_op.create_index(batch_op.f('ix_visits_user_id'), ['user_id'], unique=False)
        # Step 6: Drop the old foreign key constraint on marketer_id
        batch_op.drop_constraint('visits_marketer_id_fkey', type_='foreignkey')
        # Step 7: Create a new foreign key constraint on user_id
        batch_op.create_foreign_key('fk_visits_user_id_users', 'users', ['user_id'], ['id'])
        # Step 8: Drop the marketer_id column
        batch_op.drop_column('marketer_id')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        # Step 1: Re-add marketer_id as nullable
        batch_op.add_column(sa.Column('marketer_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # Step 2: Populate marketer_id with values from user_id
    op.execute('UPDATE visits SET marketer_id = user_id')

    with op.batch_alter_table('visits', schema=None) as batch_op:
        # Step 3: Make marketer_id NOT NULL
        batch_op.alter_column('marketer_id', nullable=False)
        # Step 4: Drop the foreign key constraint on user_id
        batch_op.drop_constraint('fk_visits_user_id_users', type_='foreignkey')
        # Step 5: Drop the index on user_id
        batch_op.drop_index(batch_op.f('ix_visits_user_id'))
        # Step 6: Create a foreign key constraint on marketer_id
        batch_op.create_foreign_key('visits_marketer_id_fkey', 'users', ['marketer_id'], ['id'])
        # Step 7: Create an index on marketer_id
        batch_op.create_index('ix_visits_marketer_id', ['marketer_id'], unique=False)
        # Step 8: Drop the user_id column
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###