"""Add additional fields to visit model

Revision ID: c4e2464bc5cb
Revises: e3a212a29746
Create Date: 2025-03-31 16:53:34.036097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e2464bc5cb'
down_revision = 'e3a212a29746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marketer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('doctor_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=False))
        batch_op.drop_index('ix_visits_doctor_id')
        batch_op.create_index(batch_op.f('ix_visits_marketer_id'), ['marketer_id'], unique=False)
        batch_op.drop_constraint('visits_doctor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['marketer_id'], ['id'])
        batch_op.drop_column('doctor_id')
        batch_op.drop_column('patient_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('visits_doctor_id_fkey', 'users', ['doctor_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_visits_marketer_id'))
        batch_op.create_index('ix_visits_doctor_id', ['doctor_id'], unique=False)
        batch_op.drop_column('location')
        batch_op.drop_column('doctor_name')
        batch_op.drop_column('marketer_id')

    # ### end Alembic commands ###
